name: weekly
on:
  push:
    branches: 
      - master
  schedule:
    - cron: 0 1 * * 0

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: shards install
    - name: Check formatting
      run: crystal tool format --check
    - name: Run tests
      run: crystal spec --error-trace -t -Dpreview_mt
